#!/usr/bin/env python
"""Drive a Kaggle GPU run headlessly, from outside Kaggle.

Kaggle kernels execute server-side, so a run started here survives this
process: the 6-hour M0 gate keeps going whether or not the machine that
launched it is still alive. That makes `push` / `status` / `fetch` three
independent commands rather than one blocking call.

Requires:
  * network egress to api.kaggle.com and www.kaggle.com
  * KAGGLE_USERNAME and KAGGLE_KEY in the environment (or ~/.kaggle/kaggle.json)

The kernel is generated as a *script*, not a notebook. Batch runs have no
interactive output to preserve, and a script's logs stream linearly, which is
what `status` polls. The notebook in notebooks/ stays the human-facing path.

Usage:
    python scripts/kaggle_remote.py push --stage smoke      # ~15 min, check fp16 health
    python scripts/kaggle_remote.py push --stage gate       # ~6 hrs, the real run
    python scripts/kaggle_remote.py status
    python scripts/kaggle_remote.py fetch --out results/
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

REPO = "https://github.com/achalshah20/microlab.git"
DEFAULT_REF = "claude/implementation-task-list-w8ce0g"

# Each stage is a separate kernel so a failure in one does not cost the others,
# and so the smoke run can be inspected before the gate burns 6 hours of quota.
STAGES = {
    "tests": ["pytest -m gpu -q"],
    "smoke": [
        "python -m microlab.cli prepare --source tinystories "
        "--out-dir /kaggle/working/data/tinystories --vocab-size 8192",
        "python scripts/kaggle_train.py --config m0 "
        "--data-dir /kaggle/working/data/tinystories --runs-dir /kaggle/working/runs "
        "train.run_id=m0_smoke train.max_steps=200 train.log_interval=10",
        "python -m microlab.cli bench m0 --steps 30 --warmup 5 "
        "--out /kaggle/working/bench_t4.json",
    ],
    "gate": [
        "python -m microlab.cli prepare --source tinystories "
        "--out-dir /kaggle/working/data/tinystories --vocab-size 8192",
        "python scripts/kaggle_train.py --config m0 "
        "--data-dir /kaggle/working/data/tinystories --runs-dir /kaggle/working/runs "
        "train.run_id=m0",
    ],
}


def build_script(stage: str, ref: str) -> str:
    steps = STAGES[stage]
    body = "\n".join(f"    {json.dumps(s)}," for s in steps)
    return f'''"""microlab {stage} run — generated by scripts/kaggle_remote.py. Do not edit here."""
import subprocess, sys, os, json, time

REF = {json.dumps(ref)}
STEPS = [
{body}
]

def run(cmd, cwd=None):
    print(f"\\n$ {{cmd}}", flush=True)
    r = subprocess.run(cmd, shell=True, cwd=cwd)
    if r.returncode != 0:
        raise SystemExit(f"step failed ({{r.returncode}}): {{cmd}}")

os.chdir("/kaggle/working")
if not os.path.exists("microlab"):
    run(f"git clone -q --branch {{REF}} {REPO} microlab")
run("pip install -q -e '.[data,dev]'", cwd="microlab")

import torch
print("torch", torch.__version__, "cuda", torch.cuda.is_available(), flush=True)
for i in range(torch.cuda.device_count()):
    p = torch.cuda.get_device_properties(i)
    print(f"  gpu{{i}}: {{p.name}} sm_{{p.major}}{{p.minor}} "
          f"{{p.total_memory/1e9:.1f}}GB bf16={{torch.cuda.is_bf16_supported()}}", flush=True)

start = time.time()
for step in STEPS:
    run(step, cwd="microlab")
print(f"\\nall steps done in {{(time.time()-start)/3600:.2f}}h", flush=True)

# Archive the run record (small: metrics, session log, samples — not checkpoints)
# so `fetch` can pull the evidence without dragging down gigabytes of weights.
if os.path.isdir("/kaggle/working/runs"):
    run("tar czf /kaggle/working/run_record.tar.gz --exclude=checkpoints -C /kaggle/working runs")
'''


def kernel_slug(stage: str) -> str:
    user = os.environ.get("KAGGLE_USERNAME")
    if not user:
        raise SystemExit(
            "KAGGLE_USERNAME is not set. Provide KAGGLE_USERNAME and KAGGLE_KEY as "
            "environment variables (from kaggle.com/settings -> API -> Create New Token)."
        )
    return f"{user}/microlab-m0-{stage}"


def write_kernel(stage: str, ref: str, workdir: Path) -> Path:
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "run.py").write_text(build_script(stage, ref))
    metadata = {
        "id": kernel_slug(stage),
        "title": f"microlab M0 {stage}",
        "code_file": "run.py",
        "language": "python",
        "kernel_type": "script",
        # Both are required and are the two settings people forget: without GPU
        # the run is 100x slower, without internet the dataset download fails.
        "enable_gpu": True,
        "enable_internet": True,
        "is_private": True,
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (workdir / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2))
    return workdir


def _kaggle(args: list[str]) -> int:
    print(f"$ kaggle {' '.join(args)}", flush=True)
    return subprocess.call([sys.executable, "-m", "kaggle", *args])


def cmd_push(args: argparse.Namespace) -> int:
    workdir = write_kernel(args.stage, args.ref, Path(args.workdir) / args.stage)
    print(f"kernel prepared in {workdir}")
    if args.dry_run:
        print((workdir / "run.py").read_text())
        return 0
    return _kaggle(["kernels", "push", "-p", str(workdir)])


def cmd_status(args: argparse.Namespace) -> int:
    slug = kernel_slug(args.stage)
    if not args.watch:
        return _kaggle(["kernels", "status", slug])
    # Poll at a cadence matched to what is being watched: a 6-hour run does not
    # need a check every 30 seconds.
    while True:
        if _kaggle(["kernels", "status", slug]) != 0:
            return 1
        time.sleep(args.interval)


def cmd_fetch(args: argparse.Namespace) -> int:
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    return _kaggle(["kernels", "output", kernel_slug(args.stage), "-p", str(out)])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    def common(p):
        p.add_argument("--stage", default="smoke", choices=sorted(STAGES))
        p.add_argument("--ref", default=DEFAULT_REF, help="git ref to run")
        p.add_argument("--workdir", default=".kaggle_kernels")

    p_push = sub.add_parser("push", help="upload and start the kernel")
    common(p_push)
    p_push.add_argument("--dry-run", action="store_true", help="generate but do not upload")
    p_push.set_defaults(func=cmd_push)

    p_status = sub.add_parser("status", help="check run status")
    common(p_status)
    p_status.add_argument("--watch", action="store_true")
    p_status.add_argument("--interval", type=int, default=300)
    p_status.set_defaults(func=cmd_status)

    p_fetch = sub.add_parser("fetch", help="download kernel output")
    common(p_fetch)
    p_fetch.add_argument("--out", default="kaggle_output")
    p_fetch.set_defaults(func=cmd_fetch)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
